### PR TITLE
Drop Twine headers

### PR DESCRIPTION
**Pull request by dwaynebailey**
Drop the injected Twine headers:

1. They introduce noise
2. Allows a smoother transition to other tools to be possible

Downside:
1. Removes a sense of this being an automated output, though JSON output has no such header (for obvious reasons)

Results can be seen here https://github.com/organicmaps/organicmaps/pull/8960

### CODE REVIEW

**Review by rtsisyk — APPROVED** [review]
Thanks for fixing discrepancies between Twine and native tools. This PR and https://github.com/organicmaps/organicmaps/pull/8960 LGTM.

**Comment by biodranik** [comment]
What kind of transition do you have in mind?

**Comment by rtsisyk** [comment]
Let's merge it and move forward. Updated strings already conflict in PRs.

**Comment by biodranik** [comment]
> What kind of transition do you have in mind?

Can you please share your plans about the transition? I do not understand why this change is needed.

**Pull request merged**
